os: linux
language: python
python:
  - "3.6"      # current default Python on Travis CI

# Pipenv caching stolen from https://github.com/dragorhast/server/commit/9533328f83e0a3a10878015f425fba92df3c289b

env:
  global:
    - VIRTUAL_ENV=$HOME/.local/share/virtualenvs/bowser-venv
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_SKIP_LOCK=1 # Speeds up build.

cache:
  pip: true
  directories:
    - "$PIP_CACHE_DIR"
    - "$PIPENV_CACHE_DIR"
    - "$HOME/.local/share/virtualenvs"
    - "$VIRTUAL_ENV"
    - "$HOME/.npm"


# command to install dependencies
install:
  - pip install pipenv
  - pip install python-coveralls
  - pipenv install --dev
# command to run tests
script:
  - bash ci-scripts/run_bowser_tests.sh
  #  - bash ci-scripts/run_bowser.sh
  #  - bash ci-scripts/test-spider.sh

#  - pushd client
#
#  - npm install
#
#  - npm run-script build
#
#  - |
#    # Don't run in BG yet -- this may be useless.
#    ## run in bg
#    #npm start &
#    #
#    ## this is the server pid
#    #NPM_SERVER_PID=$!
#
#  - popd

after_success:
  - pushd bowser
  - coveralls --data_file bowser/.coverage # Import our code coverage data