language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - bash ci-scripts/run_bowser_tests.sh
  - bash ci-scripts/run_bowser.sh
  - bash ci-scripts/test-spider.sh

after_success:
  - cd bowser/
  - coveralls # Import our code coverage data